* Editing Modes

Press enter after each of these commands

M-x refill-mode => this keeps paragraphs neat while editing.
M-x auto-fill-mode => auto-fill mode - formats paragraphs as you are writing them.
M-q fill-paragraph (try this out to show ...)
C-x u (undo)
M-x paragraph-indent-text-mode
C-p move up a line
C-f move down a line
C-f move forward a character
C-b move back a character
M-f move forward a word
M-b move back a word
C-u 10 C-f move forward 10 characters
C-u 15 C-b move back 15 characters
M-> move to the end of the file
M-< mvoe to the end of the file
M-g M-g go to line
C-e Move to the end of the line
M-e Move to the end of a sentence
C-a Move to the beginning of the line
M-a Move to the beginning of a sentence
M-} move to the end of a paragraph
M-{ move to the beginning of a paragraph
For page breaks:
C-x [ move back a page
C-x ] move forward a page
Make a page delimiter to break pages



Create a page break with C-q C-l
C-v (move down a screen)
M-v (move up a screen)
M-x goto-line enter
M-x goto-char enter
M-n repeat a command (n is the number of times you want to repeat) - hold down the alt key
I like C-u n command
C-l recenter



M-d => Kill-word (delete a word)
C-d => delete a character
C-k => kill line
M-C-k => delete from beginning of a line to the cursor.
"killing in Emacs puts deleted text into the kill ring"
C-y yank (get back what you've deleted)

Line 1.
Line 2.
Line 3.
Line 4.
C-u 4 C-p (move up 4 lines), then C-a C-u C-k (kill 4 lines), C-y (paste them back)

C-w (cut)
C-y (paste)

We can mark and cut.

This is the first line.
Line 2.
Line 3.
This is the last line. (now C-space or C-@ to set the mark), highlight all the items you want to cut, then C-w to cut, the C-y to repaste)

Kill a word backwards => M-Del, delete a whole chunk M-Shift-Backspace

C-x C-x => exchange point and mark

M-h => mark a paragraph and put cursor at the start of the paragraph. C-g to quit the mark.
C-x C-p => marks the current page

Copy text without deleting it (M-w)

M-y yank-pop (after C-y yanks previous yank)

C-w or M-w copies to clipboard

C-t transposes two letters miT

M-t transposes two words.
C-x C-t transposes two lines

Also:
M-x transpose-sentences enter
M-x transpose-paragraphs enter

M-c capitalize word when cursor is on the first letter tIm
M-u puts word in uppercase tim

M-l puts word in lowercase TIM

overwrite mode
M-x overwrite-mode enter
This is in overwrite mer

Revert buffer
M-x revert-buffer enter
M-x recover-file enter

CUA mode - you can turn this on from the menu
C-c copy
C-x cut
C-v paste

Display line numbers
M-x global-display-line-numbers-mode enter

